spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    suffix: .ftl
    template-loader-path: classpath:/templates

  profiles:
    active: local
  redis:
    host: localhost
    port: 6379