spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    suffix: .ftl
    template-loader-path: classpath:/templates
  config:
    import: application-secret.yml
  jwt:
    secret: ${spring.jwt.secret}

  profiles:
    active: local
  redis:
    host: localhost
    port: 6379